### ISSUE TITLE
Black/white? Dim/normal?

### ISSUE THREAD

**Issue by inwardmovement** [mrcaidev/tailwindcss-radix-colors#10]
You seem to have included `current` and `transparent` to the colors, but why not pure `black` and `white`?

And what do the `dim`/`normal`  black/white alpha variants correspond to? I don't see them in Radix Colors.

**Comment by mrcaidev** [comment]
`black` and `white` are now added in v1.0.1.

**Comment by mrcaidev** [comment]
There is no specific correspondence with `blacka`/`whitea` `dim`/`normal`. They are just there for consistence, and personally I don't think they would come into use in any scenario.
