### ISSUE TITLE
Dark-mode classes should attach to .dark-theme instead of :root.dark-theme

### ISSUE THREAD

**Issue by ysulyma** [mrcaidev/tailwindcss-radix-colors#11]
It seems that the dark variants attach themselves to `:root.dark-theme`. This means I need to attach `.dark-theme` to `<html>`.

However, Radix defines light variants on `:root`, `.light`, and `.light-theme`, while defining dark variants on `.dark` and `.dark-theme`. This means I need to attach `.dark-theme` to `<body>`, since `<html className="dark-theme">` can have `:root` styles take predence over `.dark-theme` styles.

**Comment by mrcaidev** [comment]
Could you please post a minimal reproduction example? I don't quite understand how `.dark-theme` is relevant. Thank you.
