### ISSUE TITLE
Alpha variants of colors are missing

### ISSUE THREAD

**Issue by SeanLatimer** [mrcaidev/tailwindcss-radix-colors#2]
Is there a reason why the alpha variants are being skipped here? https://github.com/mrcaidev/tailwindcss-radix-colors/blob/d89731ea7c17d721456bf0b4d2a31deb7d268064/src/index.js#L147 

As stated by one of the maintainers, this is the reason they exist:
> The A variants are alpha variants. This means that essentially they are to be used on top of background that may vary in colours.
They have been created in a way that makes them remain as close as possible to the original color but with baked-in alpha.
https://github.com/radix-ui/website/discussions/473#discussioncomment-3732170

**Comment by mrcaidev** [comment]
Fixed!

Handling alpha variants was a little tricky at first, and I was thinking about building a prototype of plugin ASAP.

Now alpha variants is available in v0.4.0.

**Comment by raine** [comment]
Silly question that I don't see documented.

How do you use these?

I'm trying `text-gray-a1` etc. but it's not found.

**Comment by mrcaidev** [comment]
> How do you use these?

`text-graya-1 text-graydarka-1`

**Comment by raine** [comment]
Thanks, I was confused by radix using this notation:

```css
/* Alpha colors */
var(--red-a1);
var(--red-a2);
```
