### ISSUE TITLE
Custom Color Palettes

### ISSUE THREAD

**Issue by SpencerDuball** [mrcaidev/tailwindcss-radix-colors#21]
One feature I have wanted from Radix UI was a way to provide custom palettes - and a generator for just this has been added to their website:
- https://www.radix-ui.com/colors/custom

The options do not allow specifying any additional color palettes, and I can see from the package that there are some hardcoded values for matching the preferred gray with a palette:
https://github.com/mrcaidev/tailwindcss-radix-colors/blob/master/src/colors.ts#L55

I think with the correct config object supplied to the plugin, this might be doable - is this something you would consider for the project?

**Comment by mrcaidev** [comment]
Do you mean [Custom Colors](https://tailwindcss-radix-colors.mrcai.dev/guide/custom-colors)?

**Comment by SpencerDuball** [comment]
Oh yes that is exactly what I was looking for! For some reason I figured this needed to be supplied as an option - also can you check that link once, I am seeing a blank page but did noticed this MD file in the site `docs/` folder. Thanks for this package, saves a lot of headache.
![Screenshot 2024-08-11 at 11 32 30 AM](https://github.com/user-attachments/assets/bc922314-bd00-41ea-b16c-4546e11e9552)

**Comment by mrcaidev** [comment]
Strange 404 error. This page was there when I shared the link. 🤔 I re-deployed it just now, and it should be visible now. Thanks for pointing it out!
