### ISSUE TITLE
Showcase alpha colors in the docs

### ISSUE THREAD

**Issue by kydecker** [mrcaidev/tailwindcss-radix-colors#23]
Hi!

Love Radix Colors and love this extension. Thank you for building it!

I was wanting to use some of the alpha colors from the palette and I struggled to find any examples in the docs. I had to dig into the source code to see what the formatting was like in order to get the colors to appear.

It would be great to have a table in the docs showing the syntax for different colors, shades, alpha, p3, etc.

**Comment by mrcaidev** [comment]
Thank you for your suggestions! I have now added documentation for dark, p3 and alpha variants on [Color Variants](https://tailwindcss-radix-colors.mrcai.dev/guide/color-variants) section.

**Comment by kydecker** [comment]
Thank you for the speedy update!
