### ISSUE TITLE
Feature Request: Semantic class for divide utility

### ISSUE THREAD

**Issue by lightsound** [mrcaidev/tailwindcss-radix-colors#4]
It seems that there is no semantic class for "divide" utility. I think it would be useful to have something like the following. What do you think?

```jsx
<ul className="divide-mauve-dim divide-y">
  {items.map((item) => (
    <li key={item.id}>{item}</li>
  ))}
</ul>
```

Either way, thank you for the great library!

**Comment by mrcaidev** [comment]
LGTM. Working on it now!

**Comment by mrcaidev** [comment]
LGTM. I'm working on it and hopefully it will be shipped in v0.5.0.

**Comment by jerriclynsjohn** [comment]
@mrcaidev in the divide implementation you've added a hover state for divide, and we usually do not implement hover state for separator and is not mentioned in https://www.radix-ui.com/colors/docs/palette-composition/understanding-the-scale#steps-68-borders

**Comment by mrcaidev** [comment]
> [@mrcaidev](https://github.com/mrcaidev) in the divide implementation you've added a hover state for divide, and we usually do not implement hover state for separator and is not mentioned in https://www.radix-ui.com/colors/docs/palette-composition/understanding-the-scale#steps-68-borders

Oops you are right I didn't even realize that... Thank you!

I think this should be considered a breaking change though? If so I will wait for some more features to be developed before removing the hovering divide.
